name: pytorch
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.08.22=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.12=h7f8727e_0
  - pip=23.3.1=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - audioread==3.0.1
      - certifi==2022.12.7
      - cffi==1.16.0
      - charset-normalizer==2.1.1
      - click==8.1.7
      - contourpy==1.2.0
      - cycler==0.12.1
      - decorator==5.1.1
      - filelock==3.9.0
      - fonttools==4.50.0
      - fsspec==2023.12.2
      - h5py==3.10.0
      - huggingface-hub==0.19.4
      - idna==3.4
      - importlib-resources==6.3.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - librosa==0.10.1
      - llvmlite==0.42.0
      - markupsafe==2.1.3
      - matplotlib==3.8.3
      - mpmath==1.3.0
      - msgpack==1.0.8
      - networkx==3.0
      - nltk==3.8.1
      - numba==0.59.0
      - numpy==1.26.2
      - packaging==23.2
      - pandas==2.1.4
      - pillow==9.3.0
      - platformdirs==4.2.0
      - pooch==1.8.1
      - pycparser==2.21
      - pyenchant==3.2.2
      - pyparsing==3.1.2
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - regex==2023.10.3
      - requests==2.28.1
      - safetensors==0.4.1
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - six==1.16.0
      - soundfile==0.12.1
      - soxr==0.3.7
      - sympy==1.12
      - threadpoolctl==3.3.0
      - tokenizers==0.15.0
      - torchdata==0.7.1
      - torchtext==0.16.2
      - tqdm==4.66.1
      - torchvision==0.16.2
      - transformers==4.36.1
      - triton==2.1.0
      - typing-extensions==4.4.0
      - tzdata==2023.3
      - urllib3==1.26.13
      - zipp==3.18.1
prefix: /home/huangtianhao/.conda/envs/pytorch
